objects/Alfa__c.object
<CustomObject>
    <fields>
        <fullName>Beta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beta</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Beta__c.TestPicklist__c</field>
                <operation>equals</operation>
                <value>A_v, D_v</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Beta__c</referenceTo>
        <relationshipLabel>Alfas</relationshipLabel>
        <relationshipName>Alfas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Alfa</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alfas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Beta__c.object
<CustomObject>
    <label>Beta</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Betas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BetaTest.cls
@isTest
private class BetaTest {
	
	@isTest 
	static void checkHowManySOQL() {
		Alfa__c[] alfas = new List<Alfa__c>(); 
		for( Integer i=0; i<3; i++ ){
			Alfa__c  theAlfa = new Alfa__c( Name='Alfa' + i );
			alfas.add( theAlfa );
		}
		insert alfas;
		
		Test.startTest();		
			Beta__c beta = new Beta__c( Name = 'Beta');
			insert beta;		
			System.assertEquals( 2, Limits.getQueries() );
			
		Test.stopTest();		
	}
	
}