objects/Batch_STEP__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Batch Step</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Batch_STEP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BB_C__c.object
<CustomObject>
    <fields>
        <fullName>X__c</fullName>
        <label>X</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>BB_C</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BB_Cs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X__c.object
<CustomObject>
    <label>X</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ProducerBatch.cls
global class ProducerBatch implements Database.Batchable<sObject>, Database.Stateful {
	String query = 'SELECT id, Index__c from Batch_Step__c order by Index__c';	
	public Integer counter = 10; // some initial value

	global ProducerBatch() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		counter ++; // counter should be 11 after this line
		BB_C__c bbc = new BB_C__c(
				Name = 'start',
				X__c =  String.valueOf( counter ) 
			); 		
		insert bbc;	
		return Database.getQueryLocator( query );
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		counter ++; // counter should be 12 after this line
		BB_C__c bbc = new BB_C__c(
				Name = 'execute',
				X__c =  String.valueOf( counter ) 
			); 		
		insert bbc;
	}
	
	global void finish(Database.BatchableContext BC) {
		counter ++; // counter should be 13 after this line
		BB_C__c bbc = new BB_C__c(
				Name = 'finish',
				X__c =  String.valueOf( counter ) 
			); 		
		insert bbc;
	}
	
}