objects/BB_A__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <label>Counter</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X__c</fullName>
        <label>X</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Y__c</fullName>
        <label>Y</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BB_A</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BB_A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X__c.object
<CustomObject>
    <label>X</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchPOC.cls
global class BatchPOC implements Database.Batchable<sObject> {
	
	String query = 'select Id, Name, Counter__c, Flag__c from BB_A__c order by Counter__c';
	
	global BatchPOC() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<BB_A__c> bbas = (List<BB_A__c>) scope;
		for(BB_A__c theBba : bbas){
			if(theBBa.Counter__c == 666){
				theBba.X__c = null; //it should throw an error
				theBba.Y__c = null; //it should throw an error
			}
			theBba.Flag__c = true;
		}
		update bbas;		
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}