objects/BB_A__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <label>Counter</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>BB_A</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BB_A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CleanBatch.cls
global class CleanBatch implements Database.Batchable<sObject> {
	
	String query = 'select Id, Name, Counter__c, Flag__c from BB_A__c order by Counter__c';
	
	global CleanBatch() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<BB_A__c> bbas = (List<BB_A__c>) scope;
		for(BB_A__c theBba : bbas){		
			theBba.Flag__c = false;
		}
		update bbas;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}