objects/BB_A__c.object
<CustomObject>
    <fields>
        <fullName>Counter__c</fullName>
        <label>Counter</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X__c</fullName>
        <label>X</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Y__c</fullName>
        <label>Y</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BB_A</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BB_A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/X__c.object
<CustomObject>
    <label>X</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PaginationController.cls
public with sharing class PaginationController {
    public boolean displayNext{get; private set;}
    public boolean displayPrev{get; private set;}
    public List<BB_A__c> bbas{get; private set;}	
    private Integer offsetSize = 0;
    private Integer recordLimit  = 10;

    
    public PaginationController() {
         calculateBbas();
         displayPrev = false;
         displayNext = true;
    }

    public PageReference next(){
        offsetSize = offsetSize + 10;
        calculateBbas();
        return null;
    }

    public PageReference prev(){
        offsetSize = offsetSize + 10;
         calculateBbas();
        return null;
    }

    private void calculateBbas(){
        bbas = [select Id, Name, X__c, Y__c, Flag__c, Counter__c from BB_A__c order by Counter__c limit :recordLimit offset :offsetSize];    
    }   
    
}